export type AdvancedValueActions = "file-explorer-rename-file"
    | "file-explorer-rename-folder"
    | "file-explorer-move-file"
    | "file-explorer-move-folder"
    | "file-explorer-copy-file"
    | "file-explorer-copy-folder"
    | "file-explorer-set-file-contents"