export type CompositeActions = "composite-create-file-with-mouse" 
| "composite-create-file-with-terminal"
| "composite-create-folder-with-mouse"
| "composite-create-folder-with-terminal"
| "composite-close-all-editors-with-mouse"