export type FileExplorerActions = "create-file" 
 | "open-file"
 | "rename-file"
 | "delete-file"
 | "move-file"
 | "copy-file"
 | "create-folder"
 | "rename-folder"
 | "delete-folder"
 | "toggle-folder"
 | "move-folder"
 | "copy-folder"