export type FileExplorerActions = "file-explorer-set-present-working-directory"
 | "file-explorer-set-file-contents"
 | "file-explorer-create-file" 
 | "file-explorer-open-file"
 | "file-explorer-close-file"
 | "file-explorer-rename-file"
 | "file-explorer-delete-file"
 | "file-explorer-move-file"
 | "file-explorer-copy-file"
 | "file-explorer-create-folder"
 | "file-explorer-expand-folder"
 | "file-explorer-collapse-folder"
 | "file-explorer-rename-folder"
 | "file-explorer-delete-folder"
 | "file-explorer-toggle-folder"
 | "file-explorer-move-folder"
 | "file-explorer-copy-folder"