export type SimpleKeyboardActions = "type-editor"
    | "save-editor"
    | "type-terminal"
    | "arrow-up"
    | "arrow-down"
    | "arrow-left"
    | "arrow-right"
    | "enter"
    | "tab"
    | "shift+arrow-right"
    | "shift+arrow-left"
    | "cmd+d"
    | "backspace"
    | "space";
