// TODO: a unit test to check if these are all statically within the other types would be cool
// also somehow not adding to these manually...
export const AllActionStrings = [
    // from AuthorActions
    "author-speak-before",
    "author-speak-after",
    "author-speak-during",
    "author-wait",
    // from EditorActions
    "editor-type",
    "editor-save",
    "editor-arrow-up",
    "editor-arrow-down",
    "editor-arrow-left",
    "editor-arrow-right",
    "editor-enter",
    "editor-tab",
    "editor-shift+arrow-left",
    "editor-shift+arrow-right",
    "editor-shift+arrow-down",
    "editor-shift+arrow-up",
    "editor-cmd+d",
    "editor-backspace",
    "editor-space",
    "editor-highlight-code",
    "editor-delete-line",
    "editor-command-left",
    "editor-command-right",
    "editor-command-d",
    "editor-command-c",
    "editor-command-v",
    "editor-shift-down-arrow",
    "editor-shift-up-arrow",
    // from MouseActions
    "mouse-click-filename",
    "mouse-click-terminal",
    "mouse-click-editor",
    // from FileExplorerActions
    "file-explorer-create-file",
    "file-explorer-open-file",
    "file-explorer-close-file",
    "file-explorer-rename-file",
    "file-explorer-delete-file",
    "file-explorer-move-file",
    "file-explorer-copy-file",
    "file-explorer-create-folder",
    "file-explorer-rename-folder",
    "file-explorer-delete-folder",
    "file-explorer-toggle-folder",
    "file-explorer-move-folder",
    "file-explorer-copy-folder",
    // from TerminalActions
    "terminal-open",
    "terminal-type",
    "terminal-arrow-up",
    "terminal-arrow-down",
    "terminal-arrow-left",
    "terminal-arrow-right",
    "terminal-enter",
    "terminal-tab",
    "terminal-shift+arrow-right",
    "terminal-shift+arrow-left",
    "terminal-backspace",
    "terminal-space",
    "terminal-command-left",
    "terminal-command-right",
    "terminal-command-c",
    "terminal-command-v",
];