export const RepeatableActionNames = [
    // Editor Actions
    "editor-save",
    "editor-arrow-up",
    "editor-arrow-down",
    "editor-arrow-left",
    "editor-arrow-right",
    "editor-enter",
    "editor-tab",
    "editor-shift+arrow-left",
    "editor-shift+arrow-right",
    "editor-shift+arrow-down",
    "editor-shift+arrow-up",
    "editor-cmd+d",
    "editor-backspace",
    "editor-space",
    "editor-command-left",
    "editor-command-right",
    "editor-command-d",
    "editor-command-c",
    "editor-command-v",
    "editor-shift-down-arrow",
    "editor-shift-up-arrow",
    
    // Mouse Actions
    "mouse-move-file-explorer",
    "mouse-move-editor",
    "mouse-move-terminal",
    "mouse-move-file-explorer-context-menu-new-file",
    "mouse-move-file-explorer-context-menu-new-folder",
    "mouse-move-file-explorer-file-context-menu-rename",
    "mouse-move-file-explorer-file-context-menu-delete",
    "mouse-move-file-explorer-folder-context-menu-new-file",
    "mouse-move-file-explorer-folder-context-menu-new-folder",
    "mouse-move-file-explorer-folder-context-menu-rename",
    "mouse-move-file-explorer-folder-context-menu-delete",
    "mouse-move-editor-context-menu-go-to-definition",
    "mouse-move-editor-context-menu-cut",
    "mouse-move-editor-context-menu-copy",
    "mouse-move-editor-context-menu-paste",
    "mouse-move-unsaved-changes-dialog-button-save",
    "mouse-move-unsaved-changes-dialog-button-dont-save",
    "mouse-move-unsaved-changes-dialog-button-cancel",
    "mouse-left-click",
    "mouse-double-left-click",
    "mouse-triple-left-click",
    "mouse-right-click",
    "mouse-right-double-click",
    "mouse-right-triple-click",
    
    // File Explorer Actions
    "file-explorer-enter-new-file-input",
    "file-explorer-enter-new-folder-input",
    "file-explorer-enter-rename-file-input",
    "file-explorer-enter-rename-folder-input",
    
    // Terminal Actions
    "terminal-arrow-up",
    "terminal-arrow-down",
    "terminal-arrow-left",
    "terminal-arrow-right",
    "terminal-enter",
    "terminal-tab",
    "terminal-shift+arrow-right",
    "terminal-shift+arrow-left",
    "terminal-backspace",
    "terminal-space",
    "terminal-command-left",
    "terminal-command-right",
    "terminal-command-c",
    "terminal-command-v"
]