export type MouseLocation = 'file-explorer' 
| 'file-explorer-file'
| 'file-explorer-folder' 
| 'file-explorer-context-menu-create-new-file'
| 'file-explorer-context-menu-create-new-folder'
| 'file-explorer-file-context-menu-rename'
| 'file-explorer-file-context-menu-delete'
| 'file-explorer-folder-context-menu-rename'
| 'file-explorer-folder-context-menu-delete'
| 'editor'
| 'editor-context-menu'
| 'editor-tab'
| 'editor-tab-close'
| 'terminal'
| 'terminal-tab'
| 'terminal-tab-close'
| 'terminal-context-menu'